select * from user_tables;

create table test_table (
    id int primary key,
    name varchar(100)
);

insert into test_table (id, name) values (1, 'Test Name');
insert into test_table (id, name) values (2, 'Another Name');

select * from test_table;

CREATE TABLE flashcards (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    front_text VARCHAR2(500) NOT NULL,
    back_text VARCHAR2(500) NOT NULL,
    category VARCHAR2(100),
    difficulty_level NUMBER(1) CHECK (difficulty_level BETWEEN 1 AND 5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO flashcards (front_text, back_text, category, difficulty_level) VALUES
('Hello', 'Hola', 'Greetings', 1);
INSERT INTO flashcards (front_text, back_text, category, difficulty_level) VALUES
('Good morning', 'Buenos días', 'Greetings', 1);
INSERT INTO flashcards (front_text, back_text, category, difficulty_level) VALUES
('How are you?', '¿Cómo estás?', 'Conversation', 2);
INSERT INTO flashcards (front_text, back_text, category, difficulty_level) VALUES
('Thank you', 'Gracias', 'Common Phrases', 1);
INSERT INTO flashcards (front_text, back_text, category, difficulty_level) VALUES
('Goodbye', 'Adiós', 'Greetings', 1);

COMMIT; 

commit;